# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95f95dd3ef87b6df9d6eafd829d8dd25"
name = "mongodb-app1"
handle = "mongodb-app1"
application_url = "https://brutal-temperature-ma-atm.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vijay-dev-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://brutal-temperature-ma-atm.trycloudflare.com/auth/callback",
  "https://brutal-temperature-ma-atm.trycloudflare.com/auth/shopify/callback",
  "https://brutal-temperature-ma-atm.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
